CREATE TABLE Person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(100) NOT NULL,
    year_of_birth int CHECK (year_of_birth >= 1900) NOT NULL
);

CREATE TABLE Book (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(100) NOT NULL,
    author varchar(100) NOT NULL,
    year_of_publishing int CHECK (year_of_publishing >= 1500) NOT NULL,
    person_id int REFERENCES Person(id) ON DELETE SET NULL
);